=== iamomstealer/java/HTML/part_b/student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="regNo" type="xs:string"/>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="dob" type="xs:date"/>
              <xs:element name="mobile" type="xs:string"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="course" type="xs:string"/>
              <xs:element name="year" type="xs:positiveInteger"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== iamomstealer/java/HTML/part_b/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="student.xsd">

  <student>
    <regNo>BCA202501</regNo>
    <name>Samarajit Mane</name>
    <dob>2004-09-14</dob>
    <mobile>9876543210</mobile>
    <email>samarajit@example.com</email>
    <course>BCA</course>
    <year>1</year>
  </student>

  <student>
    <regNo>BCA202502</regNo>
    <name>Ritika Sharma</name>
    <dob>2005-01-25</dob>
    <mobile>9123456789</mobile>
    <email>ritikasharma@example.com</email>
    <course>BCA</course>
    <year>1</year>
  </student>

</students>
